-- MySQL Script generated by MySQL Workbench
-- Wed May 13 22:52:46 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema readit_2020
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema readit_2020
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `readit_2020` DEFAULT CHARACTER SET utf8 ;
USE `readit_2020` ;

-- -----------------------------------------------------
-- Table `readit_2020`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `readit_2020`.`authors` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NULL,
  `biography` TEXT NULL,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `readit_2020`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `readit_2020`.`categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `readit_2020`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `readit_2020`.`posts` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NULL,
  `resume` VARCHAR(255) NULL,
  `image` VARCHAR(45) NULL,
  `content` TEXT NULL,
  `author_id` INT UNSIGNED NOT NULL,
  `categorie_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_posts_authors_idx` (`author_id` ASC),
  INDEX `fk_posts_categories1_idx` (`categorie_id` ASC),
  CONSTRAINT `fk_posts_authors`
    FOREIGN KEY (`author_id`)
    REFERENCES `readit_2020`.`authors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_categories1`
    FOREIGN KEY (`categorie_id`)
    REFERENCES `readit_2020`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `readit_2020`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `readit_2020`.`tags` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `readit_2020`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `readit_2020`.`comments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(45) NOT NULL,
  `content` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL,
  `post_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_posts1_idx` (`post_id` ASC),
  CONSTRAINT `fk_comments_posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `readit_2020`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `readit_2020`.`posts_has_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `readit_2020`.`posts_has_tags` (
  `post_id` INT UNSIGNED NOT NULL,
  `tag_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`post_id`, `tag_id`),
  INDEX `fk_posts_has_tags_tags1_idx` (`tag_id` ASC),
  INDEX `fk_posts_has_tags_posts1_idx` (`post_id` ASC),
  CONSTRAINT `fk_posts_has_tags_posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `readit_2020`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_has_tags_tags1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `readit_2020`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
